---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: sequenceiq/alpine-curl
    tag: latest

inputs:
- name: jb-pipeline-example-git

run:
  path: jb-pipeline-example-git/ci/scripts/acceptance.sh

params:
  TARGET_URL:
  PATTERN: