---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: '1.10'

inputs:
- name: jb-pipeline-example-go
- name: jb-pipeline-example-git

run:
  path: jb-pipeline-example-git/ci/scripts/unit-go.sh

