---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: slim

inputs:
- name: jb-pipeline-example-web

run:
  path: jb-pipeline-example-web/ci/scripts/unit-web.sh
